Dashboard/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;

public class InvoicesController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Dashboard/Controllers/QAController.cs
using Microsoft.AspNetCore.Mvc;

namespace Dashboard.Controllers
{
    public class QAController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;

namespace UsersMgmt.Controllers
{
    public class UsersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UsersMgmt</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Dashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">בית</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Users" asp-action="Index">ניהול משתמשים</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Invoices" asp-action="Index">חשבוניות</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="QA" asp-action="Index">Q&A</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" >
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>